/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Bon Robrick De Leon,Gian Destreza,Lenard Errol Izon
 */   
     import java.util.ArrayList;
     import java.util.List;
     import javax.swing.JOptionPane;
     import javax.swing.table.DefaultTableModel;
     import java.text.DecimalFormat;
     import java.util.Stack;
     public class MilkTea_Ordering_System extends javax.swing.JDialog {
    /**
     * Creates new form MilkTea_Ordering_System
     */
    private double totalPrice; 
    private List<String> cupsize = new ArrayList<>();
    private List<String> flavors = new ArrayList<>();
    private Stack<String> cartItems = new Stack<>();
    private static final double bobba_price = 15.00;
    private static final double nata_price = 15.00;
    private static final double small_price = 45.00;
    private static final double meduim_price = 60.00;
    private static final double large_price = 75.00;
    
   
    public MilkTea_Ordering_System(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        flavors.add("Oolong");
        flavors.add("Chai");
        flavors.add("Matcha");
        flavors.add("Honeydew");
        
        cupsize.add("Small");
        cupsize.add("Medium");
        cupsize.add("Large");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinField1 = new com.toedter.components.JSpinField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rb_oolong = new javax.swing.JRadioButton();
        rb_chai = new javax.swing.JRadioButton();
        rb_matcha = new javax.swing.JRadioButton();
        rb_honeydew = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        rbsmall = new javax.swing.JRadioButton();
        rbmeduim = new javax.swing.JRadioButton();
        rblarge = new javax.swing.JRadioButton();
        bt_add = new javax.swing.JButton();
        bt_remove = new javax.swing.JButton();
        bt_purchase = new javax.swing.JButton();
        bobaCheckBox = new java.awt.Checkbox();
        jellyCheckBox = new java.awt.Checkbox();
        rb_exit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cartTableModel = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        jLabel1.setText("TEA TYPE ");

        buttonGroup2.add(rb_oolong);
        rb_oolong.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        rb_oolong.setText("Oolong");

        buttonGroup2.add(rb_chai);
        rb_chai.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        rb_chai.setText("Chai");

        buttonGroup2.add(rb_matcha);
        rb_matcha.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        rb_matcha.setText("Matcha");
        rb_matcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_matchaActionPerformed(evt);
            }
        });

        buttonGroup2.add(rb_honeydew);
        rb_honeydew.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        rb_honeydew.setText("Honeydew");
        rb_honeydew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_honeydewActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        jLabel2.setText("Cup size ");

        buttonGroup1.add(rbsmall);
        rbsmall.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        rbsmall.setText("SMALL");
        rbsmall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbsmallActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbmeduim);
        rbmeduim.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        rbmeduim.setText("MEDUIM");

        buttonGroup1.add(rblarge);
        rblarge.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        rblarge.setText("LARGE");
        rblarge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rblargeActionPerformed(evt);
            }
        });

        bt_add.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bt_add.setText("ADD");
        bt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addActionPerformed(evt);
            }
        });

        bt_remove.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bt_remove.setText("Remove");
        bt_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_removeActionPerformed(evt);
            }
        });

        bt_purchase.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bt_purchase.setText("PlaceOrder");
        bt_purchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_purchaseActionPerformed(evt);
            }
        });

        bobaCheckBox.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bobaCheckBox.setLabel("Extra Boba");

        jellyCheckBox.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jellyCheckBox.setLabel("Nata de Coco");

        rb_exit.setText("Exit");
        rb_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_exitActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jLabel4.setText("Price");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("45");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("60");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("75");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("15");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setText("15");

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jLabel10.setText("Price");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_chai)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(rb_matcha)
                                .addComponent(rb_oolong))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(rb_honeydew)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(rblarge, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rbmeduim, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(rbsmall))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_add, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(bt_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_purchase)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(bobaCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(46, 46, 46)
                                    .addComponent(jLabel9))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jellyCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(jLabel8)))
                            .addGap(101, 101, 101))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(65, 65, 65))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(168, 168, 168)
                            .addComponent(rb_exit)
                            .addContainerGap()))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb_chai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb_oolong)
                .addGap(4, 4, 4)
                .addComponent(rb_matcha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_honeydew)
                .addContainerGap(215, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bobaCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rbsmall)
                                .addComponent(jLabel5)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jellyCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rbmeduim)
                                .addComponent(jLabel6))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rblarge, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_purchase)
                    .addComponent(bt_remove)
                    .addComponent(bt_add))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rb_exit)
                .addContainerGap())
        );

        cartTableModel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cartTableModel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cartTableModel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order List", "Price"
            }
        ));
        jScrollPane1.setViewportView(cartTableModel);
        if (cartTableModel.getColumnModel().getColumnCount() > 0) {
            cartTableModel.getColumnModel().getColumn(1).setMinWidth(50);
            cartTableModel.getColumnModel().getColumn(1).setMaxWidth(50);
        }

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 48)); // NOI18N
        jLabel3.setText("LUCKYSTAR MILKTEA ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(342, 342, 342))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rb_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_rb_exitActionPerformed

    private void bt_purchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_purchaseActionPerformed
        // TODO add your handling code here:
        placeOrder();
    }//GEN-LAST:event_bt_purchaseActionPerformed

    private void bt_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_removeActionPerformed
        // TODO add your handling code here:
        removeFromCart();
    }//GEN-LAST:event_bt_removeActionPerformed

    private void bt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addActionPerformed
        // TODO add your handling code here:
        addToCart();
    }//GEN-LAST:event_bt_addActionPerformed

    private void rbsmallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbsmallActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbsmallActionPerformed

    private void rb_matchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_matchaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_matchaActionPerformed

    private void rblargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rblargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rblargeActionPerformed

    private void rb_honeydewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_honeydewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_honeydewActionPerformed
             
    private void addToCart() {
        String selectedFlavor = "";
        String selectedSize = "";
        boolean addBoba = bobaCheckBox.getState();
        boolean addJelly = jellyCheckBox.getState();

        if (rb_oolong.isSelected()) {
        selectedFlavor = flavors.get(0);
    }
        else if (rb_chai.isSelected()) {
        selectedFlavor = flavors.get(1);
    } 
        else if (rb_matcha.isSelected()) {
        selectedFlavor = flavors.get(2);
    } 
        else if (rb_honeydew.isSelected()) {
        selectedFlavor = flavors.get(3);
    }

    if (rbsmall.isSelected()) {
        selectedSize = cupsize.get(0);
    } 
        else if (rbmeduim.isSelected()) {
        selectedSize = cupsize.get(1);
    } 
        else if (rblarge.isSelected()) {
        selectedSize = cupsize.get(2);
    }

    if (selectedFlavor.isEmpty() || selectedSize.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please select a flavor and size.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    double itemPrice = 0.0;
    if (selectedSize.equals(cupsize.get(0))) {
        itemPrice += small_price;
    } 
       else if (selectedSize.equals(cupsize.get(1))) {
        itemPrice += meduim_price;
    } 
       else if (selectedSize.equals(cupsize.get(2))) {
        itemPrice += large_price;
    }

    if (addBoba) {
        itemPrice += bobba_price;
    }
    if (addJelly) {
        itemPrice += nata_price;
    }

    String cartItem = selectedFlavor + " - Size: " + selectedSize + " - Boba: " + (addBoba ? "Yes" : "No") +
            ", Nata de Coco: " + (addJelly ? "Yes" : "No");
    String formattedPrice = new DecimalFormat("#.##").format(itemPrice);
    totalPrice += itemPrice;
    cartItems.push(cartItem);
    ((DefaultTableModel) cartTableModel.getModel()).addRow(new Object[]{cartItem, "₱" + formattedPrice});
}

    private void removeFromCart() {
     if (!cartItems.isEmpty()) {
        int selectedRow = cartTableModel.getSelectedRow();

        if (selectedRow != -1) {
            Stack<String> tempStack = new Stack<>();
            double removedPrice = 0.0;

            while (selectedRow >= 0) {
                String poppedItem = cartItems.pop();
                if (selectedRow == 0) {
                    removedPrice = extractPriceFromCartItem(poppedItem);
                } 
                else {
                    tempStack.push(poppedItem);
                }

                selectedRow--;
            }

            while (!tempStack.isEmpty()) {
                cartItems.push(tempStack.pop());
            }
            
            totalPrice -= removedPrice;

            DefaultTableModel defaultCartTableModel = (DefaultTableModel) cartTableModel.getModel();
            defaultCartTableModel.removeRow(selectedRow + 1);  // Adjusted the row index
        } else {
            JOptionPane.showMessageDialog(this, "Please select an item to remove.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "The cart is empty.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}

   private double extractPriceFromCartItem(String cartItem) {
    int priceIndex = cartItem.lastIndexOf("₱");
    if (priceIndex != -1) {
        return Double.parseDouble(cartItem.substring(priceIndex + 1));
    } else {
        return 0.0;
    }
}


   private void placeOrder() {
    StringBuilder receipt = new StringBuilder();
    receipt.append("Milk Tea Order Receipt\n\n");

    for (String cartItem : cartItems) {
        receipt.append(cartItem).append("\n");
    }

    
    JOptionPane.showMessageDialog(this, receipt.toString(), "Order Receipt", JOptionPane.INFORMATION_MESSAGE);

    cartItems.clear();
    DefaultTableModel model = (DefaultTableModel) cartTableModel.getModel();
    model.setRowCount(0);
    totalPrice = 0.0;
}
  
    /**
     * @param args the command line arguments
     */
      public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MilkTea_Ordering_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MilkTea_Ordering_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MilkTea_Ordering_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MilkTea_Ordering_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MilkTea_Ordering_System dialog = new MilkTea_Ordering_System(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Checkbox bobaCheckBox;
    private javax.swing.JButton bt_add;
    private javax.swing.JButton bt_purchase;
    private javax.swing.JButton bt_remove;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTable cartTableModel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.components.JSpinField jSpinField1;
    private java.awt.Checkbox jellyCheckBox;
    private javax.swing.JRadioButton rb_chai;
    private javax.swing.JButton rb_exit;
    private javax.swing.JRadioButton rb_honeydew;
    private javax.swing.JRadioButton rb_matcha;
    private javax.swing.JRadioButton rb_oolong;
    private javax.swing.JRadioButton rblarge;
    private javax.swing.JRadioButton rbmeduim;
    private javax.swing.JRadioButton rbsmall;
    // End of variables declaration//GEN-END:variables
 }
